-- Fill seo_keywords for published country pages: name/currency/legal-status patterns + terms mined from each country's own seo_description and content_json
UPDATE countries SET seo_keywords = 'online casinos Canada, best online casinos Canada, Canada online casino 2026, casino bonuses Canada, is online gambling legal in Canada, online gambling legal in Canada, Canada casino CAD payments' WHERE code = 'CA';
UPDATE countries SET seo_keywords = 'online casinos United States, best online casinos United States, United States online casino 2026, casino bonuses United States, is online gambling legal in United States, online gambling legal in United States, United States casino USD payments' WHERE code = 'US';
UPDATE countries SET seo_keywords = 'online casinos UK, best online casinos UK, UK online casino 2026, casino bonuses UK, is online gambling legal in UK, UK casino USD payments, Evospin casino UK' WHERE code = 'GB';
UPDATE countries SET seo_keywords = 'online casinos Germany, best online casinos Germany, Germany online casino 2026, casino bonuses Germany, is online gambling legal in Germany, online gambling legal in Germany, Germany casino USD payments, Germany licensed casino operators, Germany casino payment methods, Germany responsible gambling resources, Germany casino welcome bonuses, Germany casino game types' WHERE code = 'DE';
UPDATE countries SET seo_keywords = 'online casinos Australia, best online casinos Australia, Australia online casino 2026, casino bonuses Australia, is online gambling legal in Australia, Australia online gambling restrictions, Australia casino AUD payments, Australia responsible gambling resources, Australia casino game types' WHERE code = 'AU';
UPDATE countries SET seo_keywords = 'online casinos Brazil, best online casinos Brazil, Brazil online casino 2026, casino bonuses Brazil, is online gambling legal in Brazil, Brazil online gambling restrictions, Brazil casino BRL payments, Brazil casino Portuguese language support' WHERE code = 'BR';
UPDATE countries SET seo_keywords = 'online casinos Denmark, best online casinos Denmark, Denmark online casino 2026, casino bonuses Denmark, is online gambling legal in Denmark, online gambling legal in Denmark, Denmark casino DKK payments, Denmark casino Danish language support, Denmark licensed casino operators, Denmark casino payment methods, Denmark responsible gambling resources, Denmark casino welcome bonuses, Denmark casino game types' WHERE code = 'DK';
UPDATE countries SET seo_keywords = 'online casinos Finland, best online casinos Finland, Finland online casino 2026, casino bonuses Finland, is online gambling legal in Finland, online gambling legal in Finland, Finland casino EUR payments, Finland casino Finnish language support, Finland casino payment methods, Finland responsible gambling resources, Finland gambling regulation' WHERE code = 'FI';
UPDATE countries SET seo_keywords = 'online casinos Greece, best online casinos Greece, Greece online casino 2026, casino bonuses Greece, is online gambling legal in Greece, online gambling legal in Greece, Greece casino EUR payments, Greece casino Greek language support, Greece licensed casino operators, Greece casino payment methods, Greece responsible gambling resources, Greece casino welcome bonuses' WHERE code = 'GR';
UPDATE countries SET seo_keywords = 'online casinos Italy, best online casinos Italy, Italy online casino 2026, casino bonuses Italy, is online gambling legal in Italy, online gambling legal in Italy, Italy casino EUR payments, Italy casino Italian language support' WHERE code = 'IT';
UPDATE countries SET seo_keywords = 'online casinos Kyrgyzstan, best online casinos Kyrgyzstan, Kyrgyzstan online casino 2026, casino bonuses Kyrgyzstan, is online gambling legal in Kyrgyzstan, Kyrgyzstan online gambling restrictions, Kyrgyzstan casino KGS payments, Kyrgyzstan casino Kyrgyz language support' WHERE code = 'KG';
UPDATE countries SET seo_keywords = 'online casinos Spain, best online casinos Spain, Spain online casino 2026, casino bonuses Spain, is online gambling legal in Spain, online gambling legal in Spain, Spain casino EUR payments, Spain casino Spanish language support' WHERE code = 'ES';
UPDATE countries SET seo_keywords = 'online casinos Sweden, best online casinos Sweden, Sweden online casino 2026, casino bonuses Sweden, is online gambling legal in Sweden, online gambling legal in Sweden, Sweden casino SEK payments, Sweden casino Swedish language support' WHERE code = 'SE';
UPDATE countries SET seo_keywords = 'online casinos Turkey, best online casinos Turkey, Turkey online casino 2026, casino bonuses Turkey, is online gambling legal in Turkey, Turkey online gambling restrictions, Turkey casino TRY payments, Turkey casino Turkish language support' WHERE code = 'TR';
UPDATE countries SET seo_keywords = 'online casinos Lesotho, best online casinos Lesotho, Lesotho online casino 2026, casino bonuses Lesotho, is online gambling legal in Lesotho, online gambling legal in Lesotho, Lesotho casino LSL payments' WHERE code = 'LS';
UPDATE countries SET seo_keywords = 'online casinos São Tomé and Príncipe, best online casinos São Tomé and Príncipe, São Tomé and Príncipe online casino 2026, casino bonuses São Tomé and Príncipe, is online gambling legal in São Tomé and Príncipe, online gambling legal in São Tomé and Príncipe, São Tomé and Príncipe casino STN payments, São Tomé and Príncipe casino Portuguese language support' WHERE code = 'ST';
UPDATE countries SET seo_keywords = 'online casinos Guernsey, best online casinos Guernsey, Guernsey online casino 2026, casino bonuses Guernsey, is online gambling legal in Guernsey, online gambling legal in Guernsey, Guernsey casino GBP payments' WHERE code = 'GG';